### ISSUE TITLE
Example Sercom0SPISlave can't be compiled with Arduino IDE 1.8.19 + Adafruit Feather M0 (SAMD21) board selected

### ISSUE THREAD

**Issue by nikkadim** [lenvm/SercomSPISlave#4] opened 2022-09-16 14:54 UTC
```
c:/users/user1/appdata/local/arduino15/packages/adafruit/tools/arm-none-eabi-gcc/9-2019q4/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: core\variant.cpp.o: in function `SERCOM0_Handler':
C:\Users\user1\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.7.10\variants\feather_m0/variant.cpp:131: multiple definition of `SERCOM0_Handler'; sketch\Sercom0SPISlave.ino.cpp.o:C:\Users\user1\Documents\Arduino\libraries\SercomSPISlave\examples\Sercom0SPISlave/Sercom0SPISlave.ino:53: first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Adafruit Feather M0 (SAMD21).

```

**Comment by nikkadim** [comment] 2022-09-16 14:57
.

**Comment by lenvm** [comment] 2022-10-01 16:38
Dear @nikkadim, I have been able to reproduce your issue. The Sercom1 and Sercom4 examples don’t suffer the same problem.

The issue is also described in https://github.com/arduino/ArduinoCore-samd/issues/631 and is related to the variant.cpp file defined in the ArduinoCore-samd repository.
It also describes how to modify the variant.cpp file to circumvent the issue.

**Comment by lenvm** [comment] 2022-11-06 19:58
As this is not an issue caused by this library, I will close the issue.

**Closed as completed** 2022-11-06 19:58 UTC
